name: Build and Test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      shell: pwsh
      run: npm install
      working-directory: C:\Users\Theo\Documents\api-tests