name: Test Login Endpoint

on: [push]

jobs:
  dev-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      shell: pwsh
      run: npm install
      working-directory: ./github/workflows